name: Docker Image CI

on:
  push:
    branches: 
      - dev*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Sync README to Docker Hub Description
    #   uses: peter-evans/dockerhub-description@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    #     repository: zymoresearch/bcl-convert
    #     readme-filepath: ./README.md
#     - name: push README to Dockerhub
#       uses: christian-korneck/update-container-description-action@v1
#       env:
#           DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
#           DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
#       with:
#         destination_container_repo: zymoresearch/bcl-convert
#         provider: dockerhub
#         readme_file: 'README.md'
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: zymoresearch/bcl-convert:latest,zymoresearch/bcl-convert:3.10.5

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
